# cloudbuild.yaml
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$SHORT_SHA'
      ]

  # Step 3: Update GKE deployment to use new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/gke-rest-api',
        'gke-rest-api=us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$SHORT_SHA'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-rest-api-cluster'

# Substitute $SHORT_SHA for the short commit hash automatically
images:
  - 'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$SHORT_SHA'
