# cloudbuild.yaml

# The 'options' block MUST be at the top level (no indentation).
options:
  timeout: '1200s' # This 'timeout' field MUST be indented by exactly two spaces.

# The 'steps' block must also be at the top level (no indentation).
steps:
  # Your build steps go here, each with appropriate indentation.
  # For example:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Example Step'
    args: ['echo', 'Hello']

# The 'images' block (if present) must also be at the top level (no indentation).
images:
  # Your image list goes here.
  - 'my-artifact-repo/gke-rest-api:latest'
