# cloudbuild.yaml
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA'
      - '.'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA'

  # Step 3: Set kubectl context for GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials gke-rest-api \
          --zone us-central1-a \
          --project my-project-app-477009

  # Step 4: Update GKE deployment with new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/gke-rest-api'
      - 'gke-rest-api=us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA'

images:
  - 'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA'

timeout: '1200s'
