apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: "MTAuMzYuMzIuMTA="   # base64 of 10.36.32.10 (Private IP)
  DB_NAME: "cHJvZHVjdGRi"        # base64 of productdb
  DB_USER: "cG9zdGdyZXM="        # base64 of postgres
  DB_PASS: "cG9zdGdyZXM="        # base64 of postgres
  DB_PORT: "NTQzMg=="            # base64 of 5432
