steps:
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA', '.'
    ]

  
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA'
    ]

  
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set', 'image', 'deployment/gke-rest-api',
        'gke-rest-api=us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=product-gke-cluster'

  # 4️⃣ Verify the deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'status', 'deployment/gke-rest-api']

images:
  - 'us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:$COMMIT_SHA'
