apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: primary-node-pool
  namespace: default
spec:
  location: us-central1-a
  clusterRef:
    name: product-gke-cluster
  initialNodeCount: 2
  nodeConfig:
    machineType: e2-medium
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
  autoscaling:
    enabled: true
    minNodeCount: 1
    maxNodeCount: 4
