apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secrets-spc
  namespace: default
spec:
  provider: gcp
  parameters:
    useWorkloadIdentity: "true"  # <-- important
    secrets: |
      - resourceName: "projects/my-project-app-477009/secrets/db_password"
        fileName: "db_password"
        version: "latest"
      - resourceName: "projects/my-project-app-477009/secrets/api-key"
        fileName: "api-key"
        version: "latest"
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: db_password
          key: DB_PASS
        - objectName: api-key
          key: API_KEY
