apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    secretmanager.googleapis.com/secret-db-password: "db_password/latest"
    secretmanager.googleapis.com/secret-api-key: "api-key/latest"
type: Opaque
stringData:
  DB_HOST: "127.0.0.1"
  DB_NAME: "appdb"
  DB_USER: "user1"
  DB_PASS: ""
  API_KEY: ""
  DB_PORT: "5432"
