apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-rest-api
  labels:
    app: gke-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-rest-api
  template:
    metadata:
      labels:
        app: gke-rest-api
    spec:
      serviceAccountName: app-workload-sa
      containers:
        - name: gke-rest-api
          image: us-central1-docker.pkg.dev/my-project-app-477009/my-artifact-repo/gke-rest-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "appdb"
            - name: DB_USER
              value: "user1"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0
          args:
            - "my-project-app-477009:us-central1:products-db-instance1"
            - "--address=127.0.0.1"
            - "--port=5432"
            - "--auto-iam-authn"
            - "--private-ip"
          # Use default security context to allow access to GCP metadata
          # Do NOT set runAsNonRoot
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
