apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secret-provider
spec:
  provider: gcp
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: "projects/my-project-app-477009/secrets/db-password/versions/latest"
          objectAlias: DB_PASS
        - objectName: "projects/my-project-app-477009/secrets/api-key/versions/latest"
          objectAlias: API_KEY
  parameters:
    secrets-store.csi.k8s.io/usedefaultsa: "true"