apiVersion: v1
kind: Service
metadata:
  name: gke-rest-api-service
  labels:
    app: gke-rest-api
spec:
  type: LoadBalancer
  selector:
    app: gke-rest-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
