options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/my-project-app-477009/serviceAccounts/433503387155-compute@developer.gserviceaccount.com"

substitutions:
  _TAG: $SHORT_SHA
  _IMAGE: "us-central1-docker.pkg.dev/my-project-app-477009/my-artifact-repo/gke-rest-api"
  _DB_INSTANCE_CONNECTION: "my-project-app-477009:us-central1:product-db-instance"
  _DB_PORT: "5432"

availableSecrets:
  secretManager:
    - versionName: "projects/433503387155/secrets/cloud_sql_key/versions/latest"
      env: "_CLOUD_SQL_KEY"

steps:
  # ------------------------------------------------------
  # 0) Initialize DB via Cloud SQL Proxy
  # ------------------------------------------------------
  - name: gcr.io/cloud-builders/bash
    id: "Init DB via Cloud SQL Proxy"
    secretEnv: ["_CLOUD_SQL_KEY"]
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "ðŸ” Writing service account key..."
        echo "$_CLOUD_SQL_KEY" > /tmp/cloud_sql_key.json

        echo "ðŸš€ Starting Cloud SQL Proxy..."
        ./cloud_sql_proxy -instances=${_DB_INSTANCE_CONNECTION}=tcp:${_DB_PORT} \
          -credential_file=/tmp/cloud_sql_key.json &

        PROXY_PID=$!
        sleep 5

        echo "ðŸ”§ Loading environment variables from .env..."
        if [ -f .env ]; then
          set -o allexport
          source .env
          set +o allexport
        fi

        cd app
        pip install -r requirements.txt

        export DB_HOST=127.0.0.1
        export DB_PORT=${_DB_PORT}

        echo "ðŸš€ Initializing DB..."
        INIT_DB_ONLY=true python app.py

        echo "ðŸ›‘ Stopping Cloud SQL Proxy..."
        kill $PROXY_PID

  # ... other steps unchanged ...
